/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_pdx_svl_coDoc_poppler_lib_PopplerJNI */

#ifndef _Included_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
#define _Included_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
 * Method:    document_new_from_file
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI_document_1new_1from_1file
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
 * Method:    document_close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI_document_1close
  (JNIEnv *, jobject);

/*
 * Class:     edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
 * Method:    document_get_n_pages
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI_document_1get_1n_1pages
  (JNIEnv *, jobject);

/*
 * Class:     edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
 * Method:    document_get_page
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI_document_1get_1page
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
 * Method:    document_release_page
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI_document_1release_1page
  (JNIEnv *, jobject);

/*
 * Class:     edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
 * Method:    page_get_size
 * Signature: ()Lorg/eclipse/swt/graphics/Point;
 */
JNIEXPORT jobject JNICALL Java_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI_page_1get_1size
  (JNIEnv *, jobject);

/*
 * Class:     edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
 * Method:    page_get_index
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI_page_1get_1index
  (JNIEnv *, jobject);

/*
 * Class:     edu_pdx_svl_coDoc_poppler_lib_PopplerJNI
 * Method:    page_render
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_pdx_svl_coDoc_poppler_lib_PopplerJNI_page_1render
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
